id: P001723
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 2021-12-17 10:16:44.149627
source_metadata:
  id: bdr:W8LS18108
  title: ཡུལ་ལྷའི་རྒྱལ་པོ་གསེར་ཞལ་ཅན་གྱི་ཆོ་ག
  author: ''
  volumes:
    5497dced4b77407894f27e8ff7076969:
      image_group_id: I8LS18138
      title: ''
      volume_number: 1
      total_pages: 34
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
